name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curriculum_vitae.tex
          post_compile: "mv curriculum_vitae.pdf rolfbritten_cv.pdf"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: rolfbritten_cv
          path: rolfbritten_cv.pdf
          retention-days: 90
